name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PUBLISH_PATH: '.'
  AZURE_WEB_APP: 'github-actions-demo-api'
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish --configuration Release -o '${{env.PUBLISH_PATH}}/publish'
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: '${{env.AZURE_WEB_APP}}'
        publish-profile: '${{secrets.AZURE_APP_PUBLISH_PROFILE}}'
        package: '${{env.PUBLISH_PATH}}/publish'
 
    - name: Newman Action
      uses: matt-ball/newman-action@0.0.28
      with:
        apiKey: PMAK-5f1a33b5b0236f0042b9aec7-d5f96d4a3ab048a2b9c9f796ddf7acae18
        collection: ff1f08aa-bf27-4ffc-8d82-72dd2cc80110
        environment: 21c61307-4468-4931-9c4c-3ba2266c3cec
