name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PUBLISH_PATH: '.'
  AZURE_WEB_APP: 'github-actions-demo-api'
  POSTMAN_COLLECTION_ID: 'ff1f08aa-bf27-4ffc-8d82-72dd2cc80110'
  POSTMAN_ENV_ID: '21c61307-4468-4931-9c4c-3ba2266c3cec'
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish --configuration Release -o '${{env.PUBLISH_PATH}}/publish'
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: '${{env.AZURE_WEB_APP}}'
        publish-profile: '${{secrets.AZURE_APP_PUBLISH_PROFILE}}'
        package: '${{env.PUBLISH_PATH}}/publish'
 
    - name: Newman Action
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
        
        
    - name: Install 
      run: npm install -g newman
    
    - name: Run Newman 
      run: newman run "https://api.getpostman.com/collections/${{env.POSTMAN_COLLECTION_ID}}?apikey=${{ secrets.POSTMAN_API_KEY }}" --environment "https://api.getpostman.com/environments/${{ env.POSTMAN_ENV_ID }}?apikey=${{ secrets.POSTMAN_API_KEY }}"

